### PR TITLE
Add new functionality for API to docs

### PR DESCRIPTION
**Pull request by Oliversw**
Updates documentation to match recent changes and additions to API:
- Adds `comparison` as a new parameter for SKU and Store data requests
- Adds new /list path for fetching SKU/Filter names
- Changes `sku` to `viewby` and adds `filter` as another parameter for SKU and Store data requests
- Adds note that `retailer=all` is only valid for SKU data requests

Testing:
- Clone down repo
- Run `npm start` and you should be able to view a local version of the documentation

### CODE REVIEW

**Review by AKP-13 — CHANGES_REQUESTED** [review]
Hey @Oliversw, this looks good, just a super small thing (that's only worth looking into if it's a quick fix.. not a biggie at all)

- Noticed that clicking on **Get available metrics** and **Return data by Store** in the sidebar jump you to the section just above - maybe a link missing?

**Comment by Oliversw** [comment]
> Hey @Oliversw, this looks good, just a super small thing (that's only worth looking into if it's a quick fix.. not a biggie at all)
> 
> * Noticed that clicking on **Get available metrics** and **Return data by Store** in the sidebar jump you to the section just above - maybe a link missing?

Yeah I think this has always been the case. I thought it might have been happening because the documentation is fairly small, but I haven't been able to find the issue in the past. I think it might not be worth the dev time at the moment since it's something to do with the way that the documentation package builds the page.

**Comment by emilyprevezer** [comment]
> > Hey @Oliversw, this looks good, just a super small thing (that's only worth looking into if it's a quick fix.. not a biggie at all)
> > 
> > * Noticed that clicking on **Get available metrics** and **Return data by Store** in the sidebar jump you to the section just above - maybe a link missing?
> 
> Yeah I think this has always been the case. I thought it might have been happening because the documentation is fairly small, but I haven't been able to find the issue in the past. I think it might not be worth the dev time at the moment since it's something to do with the way that the documentation package builds the page.

Updated `operationId` and it seemed to sort this!

**Review by emilyprevezer — APPROVED** [review]
update looks good @Oliversw 🙌

**Pull request merged**
